package net.minecraft.src.orizondim.layers;
import net.minecraft.src.orizondim.*;
import net.minecraft.src.*;

public class LayerBiome extends GenLayerOrizon
{
    //public static BiomeGenBase[] biomeArray = new BiomeGenBase[] {BiomeGenBase.desert, BiomeGenBase.forest, BiomeGenBase.extremeHills, BiomeGenBase.swampland, BiomeGenBase.plains, BiomeGenBase.taiga, BiomeGenBase.jungle};

    /** this sets all the biomes that are allowed to appear in the overworld */
    private BiomeGenBase[] allowedBiomes;

    public LayerBiome(long par1, GenLayerOrizon par3GenLayer, WorldType par4WorldType)
    {
        super(par1);
        this.allowedBiomes = WorldProviderOrizon.biomes;
        this.parent = par3GenLayer;

        /*if (par4WorldType == WorldType.DEFAULT_1_1)
        {
        	this.allowedBiomes = WorldProviderOrizon.biomes;
            //this.allowedBiomes = new BiomeGenBase[] {BiomeGenBase.desert, BiomeGenBase.forest, BiomeGenBase.extremeHills, BiomeGenBase.swampland, BiomeGenBase.plains, BiomeGenBase.taiga};
        }*/
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int par1, int par2, int par3, int par4)
    {
        int[] parentInts = this.parent.getInts(par1, par2, par3, par4);
        int[] intCache = IntCache.getIntCache(par3 * par4);

        for (int var7 = 0; var7 < par4; ++var7)
        {
            for (int var8 = 0; var8 < par3; ++var8)
            {
                this.initChunkSeed((long)(var8 + par1), (long)(var7 + par2));
                int var9 = parentInts[var8 + var7 * par3];

                if (var9 == 0)
                {
                    intCache[var8 + var7 * par3] = 0;
                }
                /*else if (var9 == BiomeGenBase.mushroomIsland.biomeID)
                {
                    intCache[var8 + var7 * par3] = var9;
                }*/
                /*else if (var9 == 1)
                {
                    intCache[var8 + var7 * par3] = this.allowedBiomes[this.nextInt(this.allowedBiomes.length)].biomeID;
                }*/
                else //Defaulting here
                {
                	intCache[var8 + var7 * par3] = this.allowedBiomes[this.nextInt(this.allowedBiomes.length)].biomeID;
                    //intCache[var8 + var7 * par3] = mod_Orizon.plains.biomeID;
                }
            }
        }

        return intCache;
    }
}
